const data = {
  products: [
    {
      name: 'Scape Shirt',
      slug: 'scape-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      brand: 'Nike',
      rating: 4.5,
      price: 55,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Free Shirt',
      category: 'Shirts',
      slug: 'free-shirt',
      image: '/images/shirt2.jpg',
      brand: 'Nike',
      rating: 4.5,
      price: 55,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Smart Pants',
      category: 'Pants',
      slug: 'smart-pants',
      image: '/images/Pants1.jpg',
      brand: 'Nike',
      rating: 4.5,
      price: 55,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Fit Pants',
      category: 'Pants',
      slug: 'fit-pants',
      image: '/images/Pants2.jpg',
      brand: 'Nike',
      rating: 4.5,
      price: 55,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Classic Pants',
      category: 'Pants',
      slug: 'classic-pants',
      image: '/images/Pants3.jpg',
      brand: 'Nike',
      price: 55,
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
  ],
};
export default data;
