const data = {
  products: [
    {
      name: 'Uni Shirt',
      slug: 'uni-shirt',
      category: 'Shirts',
      image: '/images/shirt1.jpg',
      brand: 'UniCorp',
      rating: 0,
      isFeatured: true,
      featuredImage: '/images/shirt1.jpg',
      price: 55,
      numReviews: 0,
      countInStock: 20,
      description: 'A token of power',
      reviews: [],
    },
    {
      name: 'Elegance Bliss',
      category: 'Shirts',
      slug: 'elegance-bliss',
      isFeatured: true,
      featuredImage: '/images/shirt2.jpg',
      image: '/images/shirt2.jpg',
      brand: 'Elegant',
      rating: 0,
      price: 55,
      numReviews: 0,
      countInStock: 20,
      description: 'Dress to impress',
      reviews: [],
    },
    {
      name: 'Sunny Dress',
      category: 'Pants',
      slug: 'sunny-dress',
      image: '/images/pants1.jpg',
      brand: 'Sunflower',
      rating: 0,
      price: 55,
      numReviews: 0,
      countInStock: 1,
      description: 'For the perfect date',
      reviews: [],
    },
    {
      name: 'Fatty Pants',
      category: 'Pants',
      slug: 'fatty-pants',
      image: '/images/pants2.jpg',
      brand: 'Sunflower',
      rating: 0,
      price: 55,
      numReviews: 0,
      countInStock: 20,
      description: 'Skinny for presenting your strength',
      reviews: [],
    },
    {
      name: 'Classic Overall',
      category: 'Pants',
      slug: 'classic-overall',
      image: '/images/pants3.jpg',
      brand: 'Sunflower',
      price: 55,
      rating: 0,
      numReviews: 0,
      countInStock: 20,
      description: 'A hill dweller option for the ranch worker',
      reviews: [],
    },
  ],
};
export default data;
